### PR TITLE
Java/Scala interface for ECOS

### PR DESCRIPTION
**Pull request by debasish83**
Hi Alex,

I opened up the PR so that you can review the changes. I understand that you don't want to change the structure and so if you don't like it I will close the PR later. 

I will maintain the jar on maven since it has lot of goodies which will be useful for ADMM based direct solver. I am using cholesky/LU factorization right now but I would like to use Sparse LDL which I have exposed in the jar as well along with ECOS library.

Thanks.
Deb

[Review on Reviewable](https://reviewable.io/reviews/embotech/ecos/88)

### CODE REVIEW

**Comment by adomahidi** [comment]
@debasish83 I would appreciate if you would re-submit this PR to the separate repository https://github.com/embotech/ecos-java-scala. We have pulled the core ecos code and the different interfaces out into separate repos, to allow for cleaner management of the different modules.

**Comment by debasish83** [comment]
@adomahidi I will do it as soon as I get some time...Right now I am close to moving the ADMM loop out for distributed/multi-core consensus while at each worker I am using proximal quasi newton to solve the composite problem...At each worker I would also like to solve modest sized problem with ECOS...With this direction we can project ADMM + ECOS as a large scale distributed SOCP solver (assuming my experiments with ADMM consensus works)...The only issue is that I am not sure how ECOS can handle f(x)...Do you have plans to extend ECOS to handle convex functions through the quadratic approximation or your users don't really need it ? MOSEK does that I think

**Comment by mcg1969** [comment]
No, MOSEK does not do this. They supply an entirely *different* solver to handle general smooth convex functions. Their primary conic solver supports roughly the same constraint set as ECOS.

**Comment by debasish83** [comment]
Cool....so admm consensus in spark with ecos running on each worker will be useful in general as a distributed interior point solver...I will resurrect my spark + ecos flow

**Comment by debasish83** [comment]
Is ecos/java-scala now Apache licensed ? We are using AMD and LDL which are LGPL...But ECOS C core that I will call is still GPL right ? Any chance we can at least make it LGPL...With LGPL we can integrate it into Spark but with GPL it won't happen

**Comment by debasish83** [comment]
Actually I see license in ecos-java-scala is Apache...what does it mean ? 

I call ECOS C code and we have to anyway drop down to C since AMD/LDL is in C...We have to honor AMD/LDL license which is LGPL...

I need to build ecos native as well in ecos-java-scala repository to support jni for different platforms (linux/macos at least)...

In ecos-java-scala how do I access ecos native C code ?

**Comment by debasish83** [comment]
The same way as Matlab and python I guess ?

**Comment by debasish83** [comment]
I am closing this PR since the code has been migrated to https://github.com/embotech/ecos-java-scala. There is a issue tracking the migration https://github.com/embotech/ecos-java-scala/issues/1.

**Pull request closed without merging**
